[package]
name = "bevy-hello-world"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
bevy = "0.16"
wasm-bindgen = "0.2"

# Enable optimization for faster dev builds
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 1
