[package]
name = "bevy-hello-world"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14"

# Enable optimization for faster dev builds
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 1
